services:
  gimu-docusai:
    image: clusterzx/gimu-docusai
    container_name: gimu-docusai
    network_mode: bridge
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID=1000
      - PGID=1000
      - GIMU_DOCUSAI_PORT=${GIMU_DOCUSAI_PORT:-3000}
      - RAG_SERVICE_URL=http://localhost:8000
      - RAG_SERVICE_ENABLED=true
    ports:
      - "3000:${GIMU_DOCUSAI_PORT:-3000}"
    volumes:
      - gimu-docusai_data:/app/data

volumes:
  gimu-docusai_data:
